### ISSUE TITLE
出错啦

### ISSUE THREAD

**Issue by summerdreh** [stevaon/chd-daka#4]
Run python ./main-action.py
Traceback (most recent call last):
  File "/home/runner/work/chd-daka/chd-daka/./main-action.py", line 5, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/webdriver_manager/chrome.py", line 7, in <module>
    from webdriver_manager.drivers.chrome import ChromeDriver
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/webdriver_manager/drivers/chrome.py", line 1, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
Error: Process completed with exit code 1.

**Comment by voluntexi** [comment]
在requirements.txt中添加一行代码“packaging”

**Comment by stevaon** [comment]
> ## 在requirements.txt中添加一行代码“packaging”，像这样
> selenium==4.0.0a6 webdriver-manager requests packaging

谢谢，已解决！
